"""
Incident Overview — total incidents, severity/risk distributions, confidence scatter.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

st.set_page_config(page_title="Incident Overview | Mythos", layout="wide")

from dashboard.components.charts import (
    confidence_scatter_chart,
    risk_score_histogram,
    severity_distribution_chart,
    status_progression_chart,
)
from dashboard.components.filters import render_sidebar_filters
from dashboard.components.metrics import inject_css, render_export_buttons, render_incident_table, render_kpi_row
from dashboard.data_loader import compute_kpis, filter_df, latest_per_incident, load_jsonl

try:
    from reporting import assemble_report_data, build_incident_report
    _REPORTING_AVAILABLE = True
except ImportError:
    _REPORTING_AVAILABLE = False

inject_css(str(Path(__file__).parent.parent / "assets" / "style.css"))


@st.cache_data(ttl=30)
def _load():
    return load_jsonl()


df_all = _load()
filters = render_sidebar_filters(df_all)
df = filter_df(df_all, **filters)

st.markdown("# Incident Overview")
st.markdown("---")

# --- KPIs ---
kpis = compute_kpis(df)
render_kpi_row(kpis)
st.markdown("---")

if df.empty:
    st.info("No incidents match the current filters — or no data yet. "
            "Run `python core/orchestrator.py` to populate logs.")
    st.stop()

# --- Charts row 1 ---
col1, col2 = st.columns(2)
latest = latest_per_incident(df)
with col1:
    st.plotly_chart(severity_distribution_chart(latest), use_container_width=True)
with col2:
    st.plotly_chart(risk_score_histogram(latest), use_container_width=True)

# --- Charts row 2 ---
col3, col4 = st.columns(2)
with col3:
    st.plotly_chart(status_progression_chart(df_all), use_container_width=True)
with col4:
    st.plotly_chart(confidence_scatter_chart(latest), use_container_width=True)

st.markdown("---")
st.markdown("## Incident Table")
render_incident_table(latest)

st.markdown("---")
render_export_buttons(latest, label="incident_overview")

st.markdown("---")
st.subheader("📄 PDF Report Generator")

if not _REPORTING_AVAILABLE:
    st.warning("ReportLab not installed — PDF generation unavailable. Run `pip install reportlab`.")
elif "incident_id" not in latest.columns or latest.empty:
    st.info("No incident data available for report generation.")
else:
    inc_ids = list(latest["incident_id"].dropna().unique())
    with st.expander("Generate Incident Report"):
        r_col1, r_col2, r_col3 = st.columns([2, 1, 1])
        pdf_inc = r_col1.selectbox("Select Incident", inc_ids, key="pdf_inc_overview")
        pdf_by = r_col2.text_input("Generated By", "SOC Analyst", key="pdf_by_overview")
        pdf_cls = r_col3.selectbox(
            "Classification",
            ["CONFIDENTIAL", "RESTRICTED", "INTERNAL"],
            key="pdf_cls_overview",
        )

        if st.button("Generate PDF", key="btn_gen_pdf_overview"):
            row = latest[latest["incident_id"] == pdf_inc].iloc[0].to_dict()
            report_data = assemble_report_data(
                pdf_inc,
                incident_record=row,
                generated_by=pdf_by,
                classification=pdf_cls,
            )
            st.session_state["_pdf_overview"] = (build_incident_report(report_data), pdf_inc)

        cached = st.session_state.get("_pdf_overview")
        if cached:
            pdf_bytes, pdf_id = cached
            st.download_button(
                "⬇ Download PDF Report",
                data=pdf_bytes,
                file_name=f"mythos_{pdf_id}_report.pdf",
                mime="application/pdf",
                key="dl_pdf_overview",
            )
